<?php

namespace Database\Seeders;

use App\Models\Directory;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DirectorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Directory::create([
            'categorie_id'      => 1,
            'logo_servicio'     => 'images/logos/4.png',
            'image'             => 'images/maquinas/1.png',
            'model'             => '(PRO-BDR-XS)',
            'name_es'          => 'Despulpadora automática',
            'fabricacion_es'   => 'Acero inoxidable 304T.',
            'capacidad_es'     => 'A partir de 3500 kg/h o de acuerdo con necesidades del cliente o producción asignada.',
            'componentes_es'   => 'Acero inoxidable grado alimenticio.',
            'objetivo_es'      => 'La despulpadora automática está diseñada para extraer la pulpa del aguacate. Este proceso de despulpado consiste en extraer de la cascara, la mayor parte de solido.',
            'name_en'          => 'Automatic pulper',
            'fabricacion_en'   => 'Stainless steel 304T.',
            'capacidad_en'     => 'According to customer needs or assigned production.',
            'componentes_en'   => 'Food grade stainless steel.',
            'objetivo_en'      => 'The automatic Pulper is design to extract avocado pulp. This pulping process consists on extracting most of the solid from the peel.',
            'order'         =>  1,
        ]);

        Directory::create([
            'categorie_id'      => 1,
            'logo_servicio'     => 'images/logos/5.png',
            'image'             => 'images/maquinas/2.png',
            'model'             => '(PRO-MZC)',
            'name_es'          => 'Mezcladora al vacío y atmosférica',
            'fabricacion_es'   => 'Acero inoxidable 304',
            'capacidad_es'     => 'De acuerdo con necesidades del cliente o producción asignada.',
            'componentes_es'   => 'Acero inoxidable grado alimenticio.',
            'objetivo_es'      => 'Realiza el proceso de mezclado de la pulpa con componentes adicionales selectos por el cliente. MEZCLADORA DE VACÍO: Esta presentación tiene la cualidad de trabajar con vacío para llegar a tener un proceso más inocuo y una durabilidad más prolongada a los productos. MEZCLADORA ATMOSFÉRICA: Esta presentación a diferencia de la anterior no contiene cubierta.',
            'name_en'          => 'Mixer vacuum and atmospheric',
            'fabricacion_en'   => 'Acero inoxidable 304',
            'capacidad_en'     => 'According to customer needs or assigned production.',
            'componentes_en'   => 'Acero inoxidable grado alimenticio.',
            'objetivo_en'      => 'Performs the pulp mixing process with additional components selected by the customer. VACUUM MIXER: This presentation has the quality of working with a vacuum in order to have a more innocuous process and a longer durability of the products. ATMOSPHERIC MIXER: Unlike the previous one, this presentation does not contain a cover.',
            'order'         =>  2,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/6.png',
            'image'             => 'images/maquinas/3.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Banda de deshuesado y despulpado',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo con necesidades del cliente o producción asignada.',
            'componentes_es'    => 'Transmisión y componentes fabricados en acero inoxidable, banda modular o nitrilo. Motorreductor hermético, anti bacteria con protección IP 69K.',
            'objetivo_es'       => 'Esta banda está diseñada para separar cualquier tipo de pulpa, pastas, jaleas y este a su vez elimina cualquier impureza llámese semilla, huesos, cascara o piel; permite que manualmente se depositen en la parte central y así mismo descargarlo a la etapa siguiente.',
            'name_en'           => 'Boning and pulping conveyor',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => 'According to customer needs or assigned production.',
            'componentes_en'    => 'Transmission and components made of stainless steel, modular belt or nitrile. Hermetic gearmotor, anti-bacterial with IP 69K protection.',
            'objetivo_en'       => 'This conveyor is designed to separate any type of pulps, pastes, jellies, and this in turn eliminates any impurity be it seed, bones, shell or PEEL.;Be manually deposited and also unloaded.',
            'order'             =>  3,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/7.png',
            'image'             => 'images/maquinas/4.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Cortadora de mitades',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '1 línea -1 ton/hr',
            'componentes_es'    => 'Transmisión y componentes fabricados en acero inoxidable, banda modular o nitrilo. Motorreductor hermético, anti bacterial con protección IP 69K.',
            'objetivo_es'       => 'Nuestra cortadora de mitades cuenta con un disco de corte y una banda tipo dentada con componentes grado alimenticio para cortar alimentos esféricos por mitades, tales como: naranja, aguacate, melón, toronjas, limones etc.',
            'name_en'           => 'Automatic cubing machine',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => '2 líneas-2 ton/hr',
            'componentes_en'    => 'Transmission and components made of stainless steel, modular band or nitrile. Hermetic geared motor, antibacterial with IP 69K protection.',
            'objetivo_en'       => 'Our halves slicer has a cutting disc and a toothed belt with food grade components to cut spherical foods in halves, such as: oranges, avocados, melons, grapefruits, lemons, etc.',
            'order'             =>  4,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/8.png',
            'image'             => 'images/maquinas/5.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Cubicadora automática',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '600 a 1000 kg /hr',
            'componentes_es'    => 'Acero inoxidable 304',
            'objetivo_es'       => 'Este equipo sirve para automatizar el proceso de corte de frutos u hortalizas en fresco realizando cortes entre 15 y 20mm, cuenta con un sistema de fácil montaje y desmontaje para facilitar la limpieza de la misma.',
            'name_en'           => 'Automatic cubing machine',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => '600 a 1000 kg /hr',
            'componentes_en'    => 'Stainless steel 304.',
            'objetivo_en'       => 'This equipment is used to automate the process of cutting fresh fruits or vegetables, making cuts between 15 and 20mm, it has an easy assembly and disassembly system to facilitate cleaning.',
            'order'             =>  5,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/9.png',
            'image'             => 'images/maquinas/6.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Mesa vibradora separadora de cubos',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '600 a 1000 kg /hr',
            'componentes_es'    => 'Acero inoxidable 304.',
            'objetivo_es'       => 'Este equipo esta especializado en realizar la separación de cubos , mediante un sistema de vibración',
            'name_en'           => 'Cube separator vibrating table',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => '600 a 1000 kg /hr',
            'componentes_en'    => 'Stainless steel 304.',
            'objetivo_en'       => 'This equipment is specialized in separating cubes, using a vibration system.',
            'order'             =>  6,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/10.png',
            'image'             => 'images/maquinas/7.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Cepilladora de fruta',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo con necesidades del cliente o producción asignada.',
            'componentes_es'    => 'Acero inoxidable grado alimenticio, cuenta sistema de bombeo para agua y solución sanitizante con aplicación mediante boquilla de aspersión, con o sin arreador de fruta.',
            'objetivo_es'       => 'Las fabricaciones de estos equipos están diseñadas para eliminar impurezas, fertilizantes o simplemente tierra que lleve la fruta o verdura, se les puede integrar los sistemas de lavado que se requieran, así como secciones de secado para que el producto sea empacado de forma inmediata.',
            'name_en'           => 'Fruit brushing machine',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => 'According to customer needs or assigned production.',
            'componentes_en'    => 'Food grade stainless steel, it has a pumping system for water and sanitizing solution with application by spray nozzle, with or without fruit pusher.',
            'objetivo_en'       => 'Manufacturing of these equipments are designed to eliminate impurities, fertilizers or simply soil is the fruit or vegetables carry, they can be integrated with washing systems required, as well as drying sections so the product can be packed immediately.',
            'order'             =>  7,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/11.png',
            'image'             => 'images/maquinas/8.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Bandas transportadoras helicoidales',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '24 bolsas/min (cada bolsa de 1Lb)',
            'componentes_es'    => 'Transportador de 1 espiral, con dimensiones de banda de 24" con un trayecto efectivo de 16Mts. Aprox, un diámetro aprox. de 3.55m de espiral.',
            'objetivo_es'       => 'Este equipo periférico transporta alimentos sólidos, o semi sólidos, donde el volumen de producción demande grandes trayectos de transporte a una baja velocidad los productos pueden variar, velocidades pueden ser igual o menor para garantizar el óptimo trabajo.',
            'name_en'           => 'Conveyor belts helical',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => '24 bags/min (each bag of 1Lb)',
            'componentes_en'    => '1-turn conveyor, with belt dimensions of 24" with an effective path of approx. 16m, a diameter of approx. 3.55m of spiral.',
            'objetivo_en'       => 'This peripheral equipment transports solid or semi-solid foods, where the volume of production demands long transport routes at a low speed, the products may vary, speeds may be the same or less to guarantee optimal work.',
            'order'             =>  8,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/12.png',
            'image'             => 'images/maquinas/9.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Tinas de inmersión con banda de salida',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Incluye bomba hidráulica, sistema de turbulencia, banda sanitaria tipo modular con canjilones y componentes termoplásticos.',
            'objetivo_es'       => 'Este elemento es componente de los equipos de lavado y sanitizado en el cual se sumerge el producto en solución sanitizante ,anti oxidante o cualquier otra solución.',
            'name_en'           => 'Water bath with bucket elevator',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'It includes hydraulic pump, turbulence system, modular type sanitary conveyor with buckets and thermoplastic components.',
            'objetivo_en'       => 'This element is a component of the washing and sanitizing equipment in which the product is immersed in a sanitizing solution, anti-oxidant or any other solution.',
            'order'             =>  9,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/13.png',
            'image'             => 'images/maquinas/10.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Tinas de inmersión',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Incluye bomba hidráulica, sistema de turbulencia, y componentes termoplásticos.',
            'objetivo_es'       => 'Este elemento es componente de los equipos de lavado y sanitizado en el cual se sumerge el producto en solución sanitizante ,anti oxidante o cualquier otra solución.',
            'name_en'           => 'Water bath',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'It includes hydraulic pump, turbulence system and thermoplastic components.',
            'objetivo_en'       => 'This element is a component of the washing and sanitizing equipment in which the product is immersed in a sanitizing solution, anti-oxidant or any other solution.',
            'order'             =>  10,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/14.png',
            'image'             => 'images/maquinas/11.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Elevador de cangilones',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Banda dentada y componentes grado alimenticio.',
            'objetivo_es'       => 'Este elemento es componente de los equipos de lavado y sanitizado en el cual se sumerge el producto en solución sanitizante ,anti oxidante o cualquier otra solución.',
            'name_en'           => 'BUCKET ELEVATOR',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'Belt conveyor and grade components food.',
            'objetivo_en'       => 'This element is a component of the washing and sanitizing equipment in which the product is immersed in a sanitizing solution, anti-oxidant or any other solution.',
            'order'             =>  11,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/15.png',
            'image'             => 'images/maquinas/12.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Transportador de rodillos pre selección',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Rodillos de acero inoxidable o pvc de cedula, componentes y transmisión en acero inoxidable, incluye desviadores y chute.',
            'objetivo_es'       => 'Este elemento se puede fabricar para diferentes tipos de procesos: Elevador para destupado, Pum pre selección, Desbasurado.',
            'name_en'           => 'Pre-selected roller conveyor',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'Stainless steel or pvc cedula rollers, stainless steel components and transmission, including diverters and chute.',
            'objetivo_en'       => 'This element can be manufactured for different functions: Elevator for destuffing, Pum pre-sorting, Deburring.',
            'order'             =>  12,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/16.png',
            'image'             => 'images/maquinas/13.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Módulo de empaque rápido',
            'fabricacion_es'    => 'Fabricado en acero inoxidable o acero al carbón A36 o mixto.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Banda de PVC o nitrilo, rodillos de acero al carbón o inoxidable, transmisión en acero inoxidable o acero al carbón.',
            'objetivo_es'       => 'Estos módulos de empacado rápido están diseñados para realizar una clasificación de productos por medio de bandas, las cuáles distribuyen fruta o producto para realizar de una manera fácil el proceso de empacado manual de contenedores o cajas.',
            'name_en'           => 'Quick packing module',
            'fabricacion_en'    => 'Manufactured in stainless steel or carbon steel A36 or mixed.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'PVC or nitrile belt, carbon or stainless steel rollers, stainless steel or carbon steel transmission.',
            'objetivo_en'       => 'These fast packing modules are designed to carry out a classification of products by means of bands which distribute fruit or product to easily carry out the process of manual packing of containers or boxes.',
            'order'             =>  13,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/17.png',
            'image'             => 'images/maquinas/14.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Transportador elevador de rodillos',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Rodillos de acero inoxidable o pvc de cédula, componentes y transmisión en acero inoxidable.',
            'objetivo_es'       => 'Este elemento se puede fabricar para diferentes funcionamientos: Elevador para destupado, Pum pre selección, Desbasurado.',
            'name_en'           => 'Roller elevating conveyor',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'Stainless steel or pvc curtains, stainless steel components and stainless steel tramsmicion.',
            'objetivo_en'       => 'This element can be manufactured for different functions: Elevator for destuffing, Pum pre-sorting, Deburring.',
            'order'             =>  14,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/18.png',
            'image'             => 'images/maquinas/15.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Bandas transportadoras',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'De acuerdo con necesidades del cliente o producción asignada.',
            'objetivo_es'       => 'Este elemento se puede fabricar para diferentes funcionamientos: Elevador para destupado, Pum pre selección, Desbasurado.',
            'name_en'           => 'Conveyor belts',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => "According to customer needs or assigned production.",
            'objetivo_en'       => 'This element can be manufactured for different functions: Elevator for destuffing, Pum pre-sorting, Deburring.',
            'order'             =>  15,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/19.png',
            'image'             => 'images/maquinas/16.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Secador de fruta',
            'fabricacion_es'    => 'Acero al carbón.',
            'capacidad_es'      => 'De acuerdo a Producción.',
            'componentes_es'    => 'Acero al carbón .',
            'objetivo_es'       => 'Manufactura de periferico para secado de fruta, el cual se puede adaptar a líneas existentes o integrarse a proyectos llave en mano. Funcional, versatil y con un desempeño',
            'name_en'           => 'Fruit dryer',
            'fabricacion_en'    => 'Carbon steel.',
            'capacidad_en'      => 'According to Production.',
            'componentes_en'    => 'Carbon steel.',
            'objetivo_en'       => 'Manufacture of fruit drying peripheral, which can be adapted to existing lines or integrated into turnkey projects. Functional, versatile and with a high performance',
            'order'             =>  16,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/20.png',
            'image'             => 'images/maquinas/17.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Bomba de lóbulos',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '13.2 gpm a 441 gpm (galones por minuto).',
            'componentes_es'    => 'Conexiones Tri-clam cuenta con distintos sellos adecuados para cada tipo de aplicación, rotor Tri lobular o bi-wing, incluye sello frontal con el fin de proporcionar una fácil limpieza.',
            'objetivo_es'       => 'Las bombas de lóbulo son utilizadas principalmente en plantas donde es necesario movilizar fluidos y son populares debido a sus sobresalientes cualidades sanitarias que son requeridas por la industria de alimentos como también por su confiabilidad, alta eficiencia, y resistencia a la corrosión, velocidad máxima de 500 a 1000 RPM.',
            'name_en'           => 'Lobe pump',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "13.2 gpm to 441 gpm (gallons per minute).",
            'componentes_en'    => 'Tri-clam connections have different seals suitable for each type of application, Tri-lobular or bi-wing rotor, includes a front seal in order to provide easy cleaning.',
            'objetivo_en'       => 'Lobe pumps are mainly used in plants where it is necessary to move fluids and are popular due to their outstanding sanitary qualities they are required by the food industry as well as their reliability, high efficiency, and resistance to corrosion, maximum speed of 500 at 1000 rpm.',
            'order'             =>  17,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/21.png',
            'image'             => 'images/maquinas/18.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Bomba de transferencia',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '13.2 gpm a 441 gpm (galones por minuto).',
            'componentes_es'    => 'Incluye adaptador neumático de acero inoxidable, tanque de almacenamiento con conexiones para férulas y unidad de mantenimiento.',
            'objetivo_es'       => 'Las bombas de lóbulo son utilizadas principalmente en plantas donde es necesario movilizar fluidos y son populares debido a sus sobresalientes cualidades sanitarias que son requeridas por la industria de alimentos como también por su confiabilidad, alta eficiencia y resistencia a la corrosión, velocidad máxima de 500 a 1000 RPM.',
            'name_en'           => 'Transfer pump',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "13.2 gpm to 441 gpm (gallons per minute).",
            'componentes_en'    => 'It Includes stainless steel pneumatic adapter, storage tank with ferrule connections, and maintenance unit.',
            'objetivo_en'       => 'Lobe pumps are mainly used in plants where it is necessary to move fluids and are popular due to their outstanding sanitary qualities they are required by the food industry as well as their reliability, high efficiency, and resistance to corrosion, maximum speed of 500 at 1000 rpm.',
            'order'             =>  18,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/22.png',
            'image'             => 'images/maquinas/19.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Túnel de lavado y secado de cajas',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo con necesidades del cliente o producción asignada.',
            'componentes_es'    => 'Acero inoxidable grado alimenticio, incluye bombas y aspersores en la parte interna del túnel, ventiladores, tinas para solución sanitizante y agua.',
            'objetivo_es'       => 'Lavado y sanitizado de cajas provenientes del campo o posterior al proceso, además de realizar la función de secado.',
            'name_en'           => 'Washing and drying tunnel of crates',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to customer needs or assigned production.",
            'componentes_en'    => 'Food grade stainless steel, includes pumps and sprinklers in the internal part of the tunnel, fans, sanitizing solution and water tubs.',
            'objetivo_en'       => 'Washing and sanitizing of boxes coming from the field or after the process in addition to the drying process',
            'order'             =>  19,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/23.png',
            'image'             => 'images/maquinas/20.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Volteadora de cajas automática',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '18 a 30 cajas/minuto',
            'componentes_es'    => 'Acero al carbón A36, rodillos de PVC o acero inoxidable.',
            'objetivo_es'       => 'Automatiza el volteado de cajas girándolas lentamente y mantiene un ritmo de alimentación 18 a 30 cajas/minuto, cuenta con salida de caja mediante banda de rodillos.',
            'name_en'           => 'Crate washing and drying tunnel',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "18 to 30 boxes /minute",
            'componentes_en'    => 'A36 carbon steel, PVC or stainless steel rollers.',
            'objetivo_en'       => 'It automates the turning of boxes by rotating them slowly and maintains a feeding rate of 18 to 30 boxes/minute, with box exit by means of a roller conveyor.',
            'order'             =>  20,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/24.png',
            'image'             => 'images/maquinas/21.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Lavadora de cajas',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Acero inoxidable grado alimenticio, incluye bombas y aspersores en la parte interna del túnel, tinas para solución sanitizante y agua.',
            'objetivo_es'       => 'Lavado y sanitizado de cajas provenientes del campo o posterior al proceso.',
            'name_en'           => 'Box washer',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'Food grade stainless steel, includes pumps and sprinklers inside the tunnel, tubs for sanitizing solution and water.',
            'objetivo_en'       => 'Washing and sanitizing boxes from the field or after the process.',
            'order'             =>  21,
        ]);

        // Directory::create([
        //     'categorie_id'  => 1,
        //     'logo_servicio'     => 'images/logos/25.png',
        //     'image'             => 'images/maquinas/22.png',
        //     'model'             => '(PRO-CUB)',
        //     'name_es'           => 'Llenadora vertical',
        //     'fabricacion_es'    => 'Acero inoxidable 304.',
        //     'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
        //     'componentes_es'    => 'Acero inoxidable grado alimenticio, unidades de mantenimiento neumáticos, actuadores neumáticos y tubing acorde a las necesidades.',
        //     'objetivo_es'       => 'Este equipo realiza un llenado automático para que el proceso sea más rápido y eficiente por medio de tolva dosificadora y sensores, con esto asegurando el llenado deseado.',
        //     'name_en'           => 'Vertical filling machine',
        //     'fabricacion_en'    => 'Stainless steel 304.',
        //     'capacidad_en'      => "According to the client's needs.",
        //     'componentes_en'    => 'Food grade stainless steel, units of pneumatic maintenance, actuators tires and tubing according to needs.',
        //     'objetivo_en'       => 'This equipment performs automatic filling to make the process faster and more efficient by means of a dosing hopper and sensors, thus ensuring the desired filling.',
        //     'order'             =>  22,
        // ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/26.png',
            'image'             => 'images/maquinas/23.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Volteadora de cajas semiautomática',
            'fabricacion_es'    => 'Acero inoxidable 304.',
            'capacidad_es'      => '18 a 30 cajas/minuto',
            'componentes_es'    => 'Acero al carbón A36, rodillos de PVC o acero inoxidable.',
            'objetivo_es'       => 'Automatiza el volteado de cajas girándolas lentamente y mantiene un ritmo de alimentación 18 a 30 cajas/minuto.',
            'name_en'           => 'Semi-automatic case turner',
            'fabricacion_en'    => 'Stainless steel 304.',
            'capacidad_en'      => "18 to 30 boxes /minute",
            'componentes_en'    => 'A36 carbon steel, PVC or stainless steel rollers.',
            'objetivo_en'       => 'It automates the turning of boxes by turning them slowly and maintains a feeding rate of 18 to 30 boxes/minute.',
            'order'             =>  23,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/27.png',
            'image'             => 'images/maquinas/24.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Volteadora de bins',
            'fabricacion_es'    => 'Acero al carbón A36 con recubrimiento de pintura electroestática anticorrosiva.',
            'capacidad_es'      => '20 bins/hora',
            'componentes_es'    => 'Actuadores y bombas hidráulicas, reguladores de flujo, electroválvulas.',
            'objetivo_es'       => 'La volteadora de bins realiza una doble función donde cuenta con un pistón para obtener un empuje del bin y colocarlo directamente al área de volteo evitando el esfuerzo manual y con eso aportar una mayor producción al proceso; En la parte de volteo incluye actuadores hidráulicos y un área para el bin vacío.',
            'name_en'           => 'bin turner machine',
            'fabricacion_en'    => "A36 carbon steel with electrostatic anti-corrosion paint coating.",
            'capacidad_en'      => '20 bins/hour',
            'componentes_en'    => 'Hydraulic actuators and pumps, flow regulators, solenoid valves.',
            'objetivo_en'       => 'The bin turner performs a double function where it has a piston to obtain a push of the bin and place it directly to the turning area avoiding the manual effort and thus providing a higher production to the process; In the turning part it includes hydraulic actuators and an area for the empty bin.',
            'order'             =>  24,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/28.png',
            'image'             => 'images/maquinas/25.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Tolva de reciba',
            'fabricacion_es'    => 'Fabricado en acero inoxidable o acero al carbón A36 o mixto.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Compuerta deslizable frontal, incluye ajuste en la parte inferior de los soportes.',
            'objetivo_es'       => 'Este equipo está diseñado para complementar áreas en donde tienen demasiado producto a retirar: tecatas, huesos, desechos, etc.',
            'name_en'           => 'Hopper to receive',
            'fabricacion_en'    => 'Manufactured in stainless steel or carbon steel A36 or mixed.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'Front sliding gate, includes adjustment at the bottom of the supports.',
            'objetivo_en'       => 'This equipment is designed to complement areas where they have too much product to remove: tecatas, bones, waste, etc.',
            'order'             =>  25,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/29.png',
            'image'             => 'images/maquinas/26.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Tolva de deshecho con elevador helicoidal',
            'fabricacion_es'    => 'Acero al carbón A36 con recubrimiento de pintura electroestática anticorrosiva.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Incluye: escalera marina con guardas, adaptadores neumáticos para la apertura de las compuertas.',
            'objetivo_es'       => 'La función de estas tolvas es almacenar cualquier producto, materia prima o deshecho. Esté equipo incluye: un elevador de gusano y tolva de recolección.',
            'name_en'           => 'Scrap hopper with helical elevator',
            'fabricacion_en'    => 'A36 carbon steel with electrostatic anticorrosion paint coating.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'It Includes fixes ladder whith safety cage,pneumatic adapters for opening the gates.',
            'objetivo_en'       => 'The function of these hoppers is to store any product, raw material or waste. This equipment includes a worm elevator and collection hopper.',
            'order'             =>  26,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/30.png',
            'image'             => 'images/maquinas/27.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Tolva para deshecho exterior',
            'fabricacion_es'    => 'Acero al carbón A36 con recubrimiento de pintura electroestática anticorrosiva.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Incluye: escalera marina con guardas, adaptadores neumáticos para la apertura de las compuertas.',
            'objetivo_es'       => 'Utilizada para la acumulación y la recolección de desecho (hueso, cascara, etc...).',
            'name_en'           => 'Scrap hopper',
            'fabricacion_en'    => 'A36 carbon steel with electrostatic anticorrosion paint coating.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'It Includes fixes ladder whith safety cage,pneumatic adapters for opening the gates.',
            'objetivo_en'       => 'Used for the accumulation and collection of waste (bone, shell, etc...).',
            'order'             =>  27,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/31.png',
            'image'             => 'images/maquinas/28.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Tanques de almacenamiento',
            'fabricacion_es'    => 'Dependiendo del uso puede ser fabricado en acero al carbón A36 o acero inoxidable grado alimenticio.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Escotilla superior para fácil mantenimiento, salidas y entradas con conexiones para férulas.',
            'objetivo_es'       => 'Almacenar cualquier tipo de líquido o viscoso, puede ser fabricados horizontal o verticalmente al igual puede o no incluir bomba de transferencia, lóbulos o cualquier tipo de bomba de salida que sea acuerdo al producto almacenado.',
            'name_en'           => 'Storage tanks',
            'fabricacion_en'    => 'Depending on the use, it can be manufactured in carbon steel A36 or food grade stainless steel.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'Top hatch for easy maintenance, outlets and inlets with ferrule connections.',
            'objetivo_en'       => 'Store any type of liquid or viscous, can be manufactured horizontally or vertically as well as may or may not include transfer pump, lobes or any type of outlet pump according to the product stored.',
            'order'             =>  28,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/32.png',
            'image'             => 'images/maquinas/29.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Muestreadora de fruta',
            'fabricacion_es'    => 'Estructura de acero al carbón y sus partes en contacto fabricadas en acero inoxidable.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'Acero al carbón, nylamid y cuchillas de acero inoxidable.',
            'objetivo_es'       => 'Ideal para realizar cortes de frutas en trozos y así facilita el proceso de análisis en busca de plagas; Este equipo puede ser adaptado a las necesidades particulares del cliente.',
            'name_en'           => 'Fruit sampling machine',
            'fabricacion_en'    => 'Carbon steel structure and its parts in contact made of stainless steel.',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'Carbon steel, nylamid and stainless steel blades.',
            'objetivo_en'       => 'Ideal for cutting fruit into pieces and thus facilitating the analysis process in search of pests; This equipment can be adapted to the particular needs of the client.',
            'order'             =>  29,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/33.png',
            'image'             => 'images/maquinas/30.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Mesa de trabajo',
            'fabricacion_es'    => 'Dependiendo de el uso puede ser fabricado en acero al carbón A36 o acero inoxidable grado alimenticio.',
            'capacidad_es'      => 'De acuerdo a las necesidades del cliente.',
            'componentes_es'    => 'incluye niveladores para ajuste de altura.',
            'objetivo_es'       => 'Periférico de apoyo para trabajo, cuenta con un diseño ergonómico y niveladores de altura.',
            'name_en'           => 'work table',
            'fabricacion_en'    => 'Depending on the use, it can be manufactured in carbon steel A36 or food grade stainless steel',
            'capacidad_en'      => "According to the client's needs.",
            'componentes_en'    => 'includes levelers for height adjustment.',
            'objetivo_en'       => 'Work support peripheral, with ergonomic design and height levelers.',
            'order'             =>  30,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/34.png',
            'image'             => 'images/maquinas/31.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Andamios',
            'fabricacion_es'    => 'Fabricado en acero inoxidable, acero al carbón A36 o mixto. Incluye rejillas de fibra de vidrio o piso irving reforzado.',
            'capacidad_es'      => 'Incluye barandales y escaleras de acceso.',
            'componentes_es'    => 'incluye niveladores para ajuste de altura.',
            'objetivo_es'       => 'Equipo auxiliar que se emplea como plataforma de trabajo seguro en tareas en altura. Deben cumplir las condiciones generales respecto a materiales, estabilidad, resistencia, seguridad en el trabajo y seguridad en general.',
            'name_en'           => 'scaffolding',
            'fabricacion_en'    => 'Manufactured in stainless steel, A36 carbon steel or mixed. Includes fiberglass grills or reinforced irving floor.',
            'capacidad_en'      => "Includes railings and access stairs.",
            'componentes_en'    => 'includes levelers for height adjustment.',
            'objetivo_en'       => 'Auxiliary equipment used as a safe work platform for tasks at height. They must comply with the general conditions regarding materials, stability, resistance, safety at work and general safety.',
            'order'             =>  31,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/35.png',
            'image'             => 'images/maquinas/32.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Extractor de agua de coco',
            'fabricacion_es'    => 'Fabricado en acero inoxidable.',
            'capacidad_es'      => '10,000 cocos por hora.',
            'componentes_es'    => 'Acero inoxidable 304',
            'objetivo_es'       => 'La cortadora de cocos IBE SOLUTIONS está compuesta por un sistema de cinta dentada que alinea la fruta hacia un bloque de cuchillas. El sistema de transporte es giratorio y gracias a la forma de los raíles, los productos se alinean durante el transporte para ser cortados posteriormente por la mitad y así extraer el agua.',
            'name_en'           => 'Coconut water extractor',
            'fabricacion_en'    => 'Manufactured in stainless steel.',
            'capacidad_en'      => "10,000 coconuts per hour.",
            'componentes_en'    => 'Stainless steel 304.',
            'objetivo_en'       => 'The IBE SOLUTIONS coconut slicer is composed of a toothed belt system that aligns the fruit towards a block of blades. The transport system is rotating and, thanks to the shape of the rails, the products are aligned during transport to be subsequently cut in half to extract the water.',
            'order'             =>  32,
        ]);

        Directory::create([
            'categorie_id'  => 1,
            'logo_servicio'     => 'images/logos/36.png',
            'image'             => 'images/maquinas/33.png',
            'model'             => '(PRO-CUB)',
            'name_es'           => 'Triturador',
            'fabricacion_es'    => 'Acero al carbón.',
            'capacidad_es'      => '40,000 cocos por hora.',
            'componentes_es'    => 'Acero al carbón.',
            'objetivo_es'       => 'Tritura cocos enteros, fibra de coco y una gran tolva de carga, equipada con un sistema de martillos de alta calidad, que trabajan a una velocidad de rotación que reduce el consumo de energía y el ruido. El material es poderosamente desgarrado y triturado por el sistema de cuchillas de corte. El rotor está especialmente diseñado para que la trituradora sea extremadamente resistente al desgaste.',
            'name_en'           => 'Shredder',
            'fabricacion_en'    => 'Carbon steel.',
            'capacidad_en'      => "40,000 coconuts per hour.",
            'componentes_en'    => 'Carbon steel.',
            'objetivo_en'       => 'It shreds whole coconuts, coconut fiber and loading hopper, equipped with a high quality hammer system, which works at a rotation speed which reduces energy consumption and noise. The material is powerfully ripped and shredded by the cutting blade system. The rotor is specially designed to make the shredder extremely wear resistant.',
            'order'             =>  33,
        ]);
    }
}
